#!/bin/bash
#set -x

LOGFILE="fugit.log"
CONFFILE="fugit.conf"

contains(){
	for entry in $1; do
		if [ "$entry" == $2 ]; then
			return 0
		fi
	done
	return 1
}

push(){
	# Unquote the argument. This currently is a security risk. Fix it.
	REPO=$(eval echo $1)
	eval $(grep "REPO $REPO$" $CONFFILE -A 3 | tail -n +2)

	printf "%s %s: Trying to push to %s (Path %s)\n" "`date`" "$FUGIT_USER" "$1" "$REPO" "$REAL" >> $LOGFILE
	if [ -z "$REAL" ]; then
		printf "%s %s: Unknown repo, abort\n" "`date`" "$FUGIT_USER" >> $LOGFILE
		printf "FAIL"
		return 1
	fi

	if contains "$PUSH" "$FUGIT_USER"; then
		git-receive-pack $REAL
		printf "%s %s: Push accepted\n" "`date`" "$FUGIT_USER" >> $LOGFILE
	else
		printf "%s %s: Push rejected\n" "`date`" "$FUGIT_USER" >> $LOGFILE	
		printf "FAIL"
	fi
}

pull(){
	# Unquote the argument. This currently is a security risk. Fix it.
	REPO=$(eval echo $1)
	eval $(grep "REPO $REPO$" $CONFFILE -A 3 | tail -n +2)

	printf "%s %s: Trying to read from %s (Path %s)\n" "`date`" "$FUGIT_USER" "$1" "$REAL" >> $LOGFILE
	if [ -z "$REAL" ]; then
		printf "%s %s: Unknown repo, abort\n" "`date`" "$FUGIT_USER" >> $LOGFILE
		printf "FAIL"
		return 1
	fi


	if contains "$PULL" "$FUGIT_USER"; then
		git-upload-pack $REAL
		printf "%s %s: Pull accepted\n" "`date`" "$FUGIT_USER" >> $LOGFILE
	else
		printf "%s %s: Pull rejected\n" "`date`" "$FUGIT_USER" >> $LOGFILE	
		printf "FAIL"
	fi
}

FUGIT_USER=$1
if [ -z "$FUGIT_USER" ]; then
	printf "%s UNKNOWN: No user name supplied\n" "`date`" >> $LOGFILE
fi

printf "%s %s: Command is %s\n" "`date`" "$FUGIT_USER" "$SSH_ORIGINAL_COMMAND" >> $LOGFILE
if [[ "$SSH_ORIGINAL_COMMAND" == "git-receive-pack "* ]]; then
	REPO=${SSH_ORIGINAL_COMMAND:17}
	printf "%s %s: push to repo %s\n" "`date`" "$FUGIT_USER" "$REPO" >> $LOGFILE
	push "$REPO"
else
	if [[ "$SSH_ORIGINAL_COMMAND" == "git-upload-pack "* ]]; then
		REPO=${SSH_ORIGINAL_COMMAND:16}
		printf "%s %s: pull from repo %s\n" "`date`" "$FUGIT_USER" "$REPO" >> $LOGFILE
		pull "$REPO"
	else
		printf "%s %s: Unknown command %s\n" "`date`" "$FUGIT_USER" "$SSH_ORIGINAL_COMMAND" >> $LOGFILE
		exit 1
	fi
fi
